machine:
  timezone: Asia/Tokyo

  node:
    version: 4.4.1

  environment:
    AWS_REGION: ap-northeast-1
    AWS_PROFILE: serverless-circleci_dev

  hosts:   #/etc/hostsを書き換える
    dev.hogehoge.com: 127.0.0.1

checkout:
  post:
    - npm run aws_init
    - bash scripts/circleci_env
    - bash scripts/aws_init

test:
  override:
    - npm test

deployment:
  production:
    branch: production
    commands:
      - npm run deploy_prod
  staging:
    branch: master
    commands:
      - npm run deploy_staging

