general:
  branches:
    ignore:
      - gh-pages

machine:
  timezone: Asia/Tokyo

  node:
    version: 0.12.0
    
  hosts:   #/etc/hostsを書き換える
    dev.hogehoge.com: 127.0.0.1

test:
  pre:
    - npm run build
  override:
    - npm test

