machine:
  timezone: Asia/Tokyo

  node:
    version: 4.4.1

  hosts:   #/etc/hostsを書き換える
    dev.hogehoge.com: 127.0.0.1

test:
  pre:
    - npm run build
  override:
    - npm test

deployment:
  production:
    branch: production
    commands:
      - npm run deploy_prod
  staging:
    branch: master
    commands:
      - npm run deploy_staging

